### ISSUE TITLE
NPC test statistics, daily fraction positive

### ISSUE THREAD

**Issue by johanrung** [pekrau/DataGraphics#148]
When hovering mouse over a bar, the fraction % figure should be rounded to two decimals.

**Comment by pekrau** [comment]
Due to inherent limitations of the underlying Vega-Lite system (it's declarative, meaning that one asks it to display stuff, and Vega-Lite figures it out, sometimes not exactly what one actually wanted), setting the number of decimals in the tooltip (hover) **also** sets it for the axis legend. So the best compromise was to set it to one decimal, in my judgement.
