### ISSUE TITLE
Why does not the CRUSH datafile upload to create dataset?

### ISSUE THREAD

**Issue by pekrau** [pekrau/DataGraphics#181]

**Comment by akochari** [comment]
Datagraphics complains about wrong type when it sees:
- NA values. Instead, it accepts if "a cell" is just left empty. (i.e., 'first_value,,third_col' instead of 'first_col,NA,third_value'
- Column starts out with integers and then a float appears.

Datagraphics gives Internal Server Error when it sees:
- columns without a name
